services:
  - type: web
    name: premium-engineer-main
    env: node
    branch: main
    root: premium-engineer-main
    buildCommand: "npm install && npm run build"
    startCommand: "node .output/server/index.mjs"