services:
  - type: static
    name: premium-engineer-main
    env: static
    branch: main
    root: premium-engineer-main
    buildCommand: "npm install && npm run build"
    publishPath: ".output/public"