services:
  - type: web
    name: premium-engineer-main
    env: node
    branch: main
    root: premium-engineer-main
    buildCommand: "cd premium-engineer-main && NITRO_PRESET=node-server npm ci && NITRO_PRESET=node-server npm run build"
    startCommand: "cd premium-engineer-main && node .output/server/index.mjs"